// Generated by scripts/build-scene-images.mjs.
export const sceneImages: Record<string, { width: number; height: number; variants: { src: string; width: number }[] }> = {
  "/images/projects/loop-hero.png": {
    "width": 1585,
    "height": 992,
    "variants": [
      {
        "src": "/images/scenes/loop-hero-480.webp",
        "width": 480
      },
      {
        "src": "/images/scenes/loop-hero-800.webp",
        "width": 800
      },
      {
        "src": "/images/scenes/loop-hero-1200.webp",
        "width": 1200
      },
      {
        "src": "/images/scenes/loop-hero-1585.webp",
        "width": 1585
      }
    ]
  },
  "/images/projects/grow-hero.png": {
    "width": 1586,
    "height": 992,
    "variants": [
      {
        "src": "/images/scenes/grow-hero-480.webp",
        "width": 480
      },
      {
        "src": "/images/scenes/grow-hero-800.webp",
        "width": 800
      },
      {
        "src": "/images/scenes/grow-hero-1200.webp",
        "width": 1200
      },
      {
        "src": "/images/scenes/grow-hero-1586.webp",
        "width": 1586
      }
    ]
  },
  "/images/projects/hive-hero.png": {
    "width": 1586,
    "height": 992,
    "variants": [
      {
        "src": "/images/scenes/hive-hero-480.webp",
        "width": 480
      },
      {
        "src": "/images/scenes/hive-hero-800.webp",
        "width": 800
      },
      {
        "src": "/images/scenes/hive-hero-1200.webp",
        "width": 1200
      },
      {
        "src": "/images/scenes/hive-hero-1586.webp",
        "width": 1586
      }
    ]
  },
  "/images/projects/rise-hero.png": {
    "width": 1586,
    "height": 992,
    "variants": [
      {
        "src": "/images/scenes/rise-hero-480.webp",
        "width": 480
      },
      {
        "src": "/images/scenes/rise-hero-800.webp",
        "width": 800
      },
      {
        "src": "/images/scenes/rise-hero-1200.webp",
        "width": 1200
      },
      {
        "src": "/images/scenes/rise-hero-1586.webp",
        "width": 1586
      }
    ]
  },
  "/images/projects/mend-hero.png": {
    "width": 1586,
    "height": 992,
    "variants": [
      {
        "src": "/images/scenes/mend-hero-480.webp",
        "width": 480
      },
      {
        "src": "/images/scenes/mend-hero-800.webp",
        "width": 800
      },
      {
        "src": "/images/scenes/mend-hero-1200.webp",
        "width": 1200
      },
      {
        "src": "/images/scenes/mend-hero-1586.webp",
        "width": 1586
      }
    ]
  },
  "/images/projects/clarke-hero.png": {
    "width": 1991,
    "height": 789,
    "variants": [
      {
        "src": "/images/scenes/clarke-hero-480.webp",
        "width": 480
      },
      {
        "src": "/images/scenes/clarke-hero-800.webp",
        "width": 800
      },
      {
        "src": "/images/scenes/clarke-hero-1200.webp",
        "width": 1200
      },
      {
        "src": "/images/scenes/clarke-hero-1600.webp",
        "width": 1600
      }
    ]
  },
  "/images/future/river-civilization.webp": {
    "width": 1536,
    "height": 1024,
    "variants": [
      {
        "src": "/images/scenes/river-civilization-480.webp",
        "width": 480
      },
      {
        "src": "/images/scenes/river-civilization-800.webp",
        "width": 800
      },
      {
        "src": "/images/scenes/river-civilization-1200.webp",
        "width": 1200
      },
      {
        "src": "/images/scenes/river-civilization-1536.webp",
        "width": 1536
      }
    ]
  },
  "/images/future/food.webp": {
    "width": 1024,
    "height": 1536,
    "variants": [
      {
        "src": "/images/scenes/food-480.webp",
        "width": 480
      },
      {
        "src": "/images/scenes/food-800.webp",
        "width": 800
      },
      {
        "src": "/images/scenes/food-1024.webp",
        "width": 1024
      }
    ]
  },
  "/images/future/movement.webp": {
    "width": 1024,
    "height": 1536,
    "variants": [
      {
        "src": "/images/scenes/movement-480.webp",
        "width": 480
      },
      {
        "src": "/images/scenes/movement-800.webp",
        "width": 800
      },
      {
        "src": "/images/scenes/movement-1024.webp",
        "width": 1024
      }
    ]
  }
};
