import { getI18n } from "@/i18n/server";
import { lifeFramework } from "@/data/story";
import Button from "@/components/ui/Button";
import SceneImage from "@/components/ui/SceneImage";
export async function BuildingLife() {
 const { t } = await getI18n();
 return <section id="mogelijkheden" className="life-story section" aria-labelledby="life-heading"><p className="eyebrow">{t("Een leven bouwen")}</p><div className="story-heading"><h2 id="life-heading">{t("Een goed leven bouw je niet uit losse onderdelen.")}</h2><p>{t("Voedsel, gezondheid, vaardigheden en een plek om te wonen raken elkaar. BOUW gebruikt die samenhang als kader om praktische plannen te ontwikkelen.")}</p></div><ol className="life-sequence">{lifeFramework.map((step,index)=><li key={step.title}><span className="eyebrow" aria-hidden="true">{String(index+1).padStart(2,"0")}</span><h3>{t(step.title)}</h3><p>{t(step.description)}</p></li>)}</ol><p className="story-boundary">{t("Dit is een denkkader, geen bewezen causale keten en geen verplichte levensroute. Mensen bouwen verschillende levens. Een goed systeem geeft hun meer keuze, niet minder.")}</p><blockquote>{t("BOUW bouwt mogelijkheden, geen verplichtingen.")}</blockquote></section>;
}
export async function BouwjaarChapter() {
 const { t, l } = await getI18n();
 return <section id="bouwjaar" className="story-feature section" aria-labelledby="bouwjaar-heading"><div className="story-feature-copy"><p className="eyebrow">{t("Vroeg beginnen / een concept om te onderzoeken")}</p><h2 id="bouwjaar-heading">BOUWJAAR</h2><p className="story-statement">{t("Ontdek wat je kunt. Bouw aan wie je wilt worden.")}</p><p>{t("Een vroeg concept om jongeren meer te laten ervaren: bewegen, koken, omgaan met geld, praktische vaardigheden, technologie en samenwerken. Niet om iedereen dezelfde richting op te sturen, maar om sterke kanten en mogelijke volgende stappen te ontdekken.")}</p><p className="story-boundary">{t("Leeftijd, duur, deelnamevorm, uitvoering en financiering staan nog open. Er bestaat nog geen BOUWJAAR-programma.")}</p><Button href={l("/bouwjaar")} build>{t("Verken BOUWJAAR")}</Button></div><figure className="story-feature-art"><SceneImage src="/images/future/movement.webp" alt={t("Conceptbeeld bij beweging en persoonlijke ontwikkeling")} sizes="(max-width: 767px) 100vw, 45vw" /><figcaption className="image-caption">{t("Conceptbeeld / geen bestaand BOUWJAAR-programma")}</figcaption></figure></section>;
}
export async function LoopChapter() {
 const { t, l } = await getI18n();
 return <section id="loop" className="story-feature story-loop section" aria-labelledby="loop-heading"><figure className="story-feature-art"><SceneImage src="/images/future/food.webp" alt={t("Conceptbeeld van verse voeding voor dagelijkse maaltijden")} sizes="(max-width: 767px) 100vw, 45vw" /><figcaption className="image-caption">{t("Conceptbeeld / geen bestaande LOOP-bezorgdienst")}</figcaption></figure><div className="story-feature-copy"><p className="eyebrow">{t("Een praktische basis / voedsel")}</p><p className="story-transition">{t("Mensen krijgen meer ruimte om iets op te bouwen als de basis van het dagelijks leven, zoals voedzaam eten, beter bereikbaar wordt.")}</p><h2 id="loop-heading">LOOP</h2><p className="story-statement">{t("De melkboer van toen. Voor het verse eten van morgen.")}</p><p>{t("De ambitie: regelmatig een betaalbaar pakket vers, voedzaam eten bij je thuis. Geproduceerd zo lokaal als praktisch mogelijk, met regionale distributie en kassen dichtbij steden waar dat zinvol blijkt. Minder gedoe rond de dagelijkse maaltijd, met ruimte om zelf te kiezen wat je eet.")}</p><p className="story-boundary">{t("Dit is een toekomstbeeld, geen werkende bezorgdienst. Betaalbaarheid, productie en bezorging moeten nog worden getoetst; bestaande winkels en afhaalpunten blijven mogelijke alternatieven.")}</p><Button href={l("/projecten/loop")} build>{t("Ontdek LOOP")}</Button></div></section>;
}
